### PR TITLE
Update names and add theme colors for full theme

### PR DESCRIPTION
**Pull request by jackiehluo**
Here's another one for these! Thanks!

screen shot 2016-03-03 at 2 12 44 pm
screen shot 2016-03-03 at 2 12 38 pm

### CODE REVIEW

**Comment by edipox** [comment]
Thank you @jackiehluo

**Comment by GeniusUnleashed** [comment]
Hey, I'm a noob to Github. I dl'd the theme last week. How do I dl the changes?

**Comment by edipox** [comment]
Hi @GeniusUnleashed 

What you did? Do you want to install the theme? If so:

## Installation
1. Download the [Nylas N1](https://nylas.com/n1) email client!
2. Clone this repo or [Download as zip](https://github.com/edipox/elementary-nylas/archive/master.zip)
3. If you downloaded the zip file you have to unzip it. 
4. On the N1 menu, select `Preferences > General > Select theme > Install new theme...`.
5. Find the directory for this theme, there 2 sub directories ElementarySoft and ElementaryFull, select one of them to install it. :tada:

**Comment by GeniusUnleashed** [comment]
I kept looking for a download button on this page for the update. I finally went back to the code page and just redownloaded it. That .zip on teh code page is the updated version, correct?

**Pull request merged**
